### PR TITLE
RHMAP-17487 fix saml cordova template issue on onprem bf

### PR DESCRIPTION
**Pull request by jcesarmobile**

### CODE REVIEW

**Comment by luigizuccarelli** [comment]
@odra - can we cherry-pick this to the FH-v4.5 branch and then close this ticket

**Comment by jcesarmobile** [comment]
@luigizuccarelli it's already there and merged https://github.com/feedhenry-templates/saml-cordova-app/pull/29

**Comment by luigizuccarelli** [comment]
@jcesarmobile - excellent thanks I wil lclose the related JIRA then

**Comment by jcesarmobile** [comment]
@luigizuccarelli I already closed it

**Pull request merged**
