### PR TITLE
Revert "Merge branch 'RHMAP-7022' 

### PR DESCRIPTION
**Pull request by secondsun**
To test : Make sure this builds in studio (3.13 branch) and doesn't use npm'd fh-js=sdk

### CODE REVIEW

**Comment by danielpassos** [comment]
I have deploy it using https://github.com/feedhenry/fh-template-apps/pull/225 and tested in  http://testing.client2.skunkhenry.com/#projects/5arxrpgitkcki5efypq4irdo/apps/5arxrph2lduopy3mkcqlopqx/build

@mmurphy Can I merge it?

PS: I will send a new one to fh-template-apps/fhcap after merge all [RHMAP-9429](https://issues.jboss.org/browse/RHMAP-9429) PRs

**Comment by mmurphy** [comment]
@danielpassos only merge if there won't be a long delay getting fh-template-apps up to date.
I presume that there won't be since you seem to have 7 of the 8 listed PRs ready? 
If there will be a delay getting all the PRs merged then I suggest merging the 7 already done and update fh-template-apps for those first.

**Comment by secondsun** [comment]
@mmurphy I'm confused, what needs to be updated in fh-template-apps?

**Comment by mmurphy** [comment]
@secondsun Since it's the fh-template-apps component that is deployed, it needs to be rebuilt, and referenced from fhcap, to include the updated templates in the platform.

**Pull request merged**
