### PR TITLE
RHMAP-7022 added fh-js-sdk as npm dependency

### PR DESCRIPTION
**Pull request by jcesarmobile**

### CODE REVIEW

**Comment by jcesarmobile** [comment]
@danielpassos @secondsun can you review?

**Comment by secondsun** [comment]
@jcesarmobile Can you share with me a fhconfig.json and project where I can test this?

**Comment by danielpassos** [comment]
@secondsun @jcesarmobile Not sure if we still having a SAML server to really test it

**Comment by jcesarmobile** [comment]
Deployed on http://testing.juliolarge.skunkhenry.com/#projects

But I'm not sure how to test the SAML, I couldn't make the old template work before making the changes.

**Comment by secondsun** [comment]
@jcesarmobile When I run the project on Android I get this error "Uncaught TypeError: $fh._getDeviceId is not a function", source: file:///android_asset/www/main.js ".

I did a npm install, cordova platform add android, and build the project with gradle.

**Comment by jcesarmobile** [comment]
Right, forgot to add this `var $fh = require('fh-js-sdk');`

**Comment by matskiv** [comment]
Tried it on Android, started OK :+1:

**Pull request merged**
